[workspace]

members = [
    "app",
    "client",
    "cloudflare",
]

[workspace.dependencies]
app = { path = "./app", default-features = false, version = "0.0.1" }

leptos = { git = "https://github.com/leptos-rs/leptos", default-features=false }