[package]
name = "app"
authors = [""]
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { git = "https://github.com/gbj/leptos", default-features = false }

[features]
default = ["hydrate"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]